#!/usr/bin/env python
"""
Regenerates CMAKE/<MODULE>_SOURCES.cmake by scanning ENGINE/<MODULE>/.

Run whenever source files are added or removed under ENGINE/.
The generated .cmake files ARE checked in (they are the contract between
CMake and the file tree).

Mirrors the pattern used in RD/PULSAR_2.1 HELPER_SCRIPTS/regenSource.py,
adapted for WEB_SYNTH's ENGINE/<MODULE>/ layout.
"""

from pathlib import Path

REPO_ROOT  = Path(__file__).resolve().parent.parent
ENGINE_DIR = REPO_ROOT / "ENGINE"
CMAKE_DIR  = REPO_ROOT / "CMAKE"

SOURCE_EXTS = (".cpp", ".h", ".hpp", ".cc")


def collect_sources(module_dir: Path) -> list[str]:
    files = []
    for path in module_dir.rglob("*"):
        if path.is_file() and path.suffix in SOURCE_EXTS:
            rel = path.relative_to(REPO_ROOT).as_posix()
            files.append(rel)
    files.sort()
    return files


def write_cmake_list(module_name: str, files: list[str]) -> Path:
    out_path = CMAKE_DIR / f"{module_name}_SOURCES.cmake"
    var_name = f"{module_name}_SOURCES"
    if files:
        # Prefix each path with ${CMAKE_SOURCE_DIR}/ so the list works regardless
        # of which CMakeLists.txt include()s the file.
        body = "\n    ".join(f"${{CMAKE_SOURCE_DIR}}/{f}" for f in files)
        content = f"# Generated by SCRIPTS/regenSource.py — do not hand-edit.\nset({var_name}\n    {body}\n)\n"
    else:
        content = f"# Generated by SCRIPTS/regenSource.py — do not hand-edit.\nset({var_name}\n    # No files found\n)\n"
    out_path.write_text(content, encoding="utf-8")
    return out_path


def main() -> None:
    if not ENGINE_DIR.is_dir():
        print(f"regenSource: ENGINE/ not found at {ENGINE_DIR}")
        return

    CMAKE_DIR.mkdir(exist_ok=True)

    modules = sorted(p for p in ENGINE_DIR.iterdir() if p.is_dir())
    if not modules:
        print("regenSource: no modules under ENGINE/")
        return

    for module_dir in modules:
        module_name = module_dir.name
        files = collect_sources(module_dir)
        out = write_cmake_list(module_name, files)
        print(f"  {out.relative_to(REPO_ROOT).as_posix()}: {len(files)} file(s)")


if __name__ == "__main__":
    main()
